nama = input("Nama Lengkap: ")
nim = input("NIM: ")
ttl = input("TTL: ")
alamat = input("Alamat: ")
no = input("No.Hp: ")
prodi = input("program Studi: ")
hobi = input("Hobi: ")
print("Biodata Diri")
print("Nama Lengkap:"+nama)
print("NIM: "+nim)
print("TTL: "+ttl)
print("Alamat: "+alamat)
print("NO. Hp: "+no)
print("Program Studi: "+prodi)
print("Hobi: "+hobi)
